branch-defaults:
  default:
    environment: ModanisaExternal-env
  master:
    environment: ModanisaExternal-env
environment-defaults:
  ModanisaExternal-env:
    branch: null
    repository: null
global:
  application_name: modanisa_external
  default_ec2_keyname: modanisa_external
  default_platform: PHP 7.2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application



  